name: Spotify YouTube Sync
description: Sync Spotify Top 50 Global playlist to YouTube (one-shot)
version: "1.0.4"
slug: spotify_yt_sync
url: https://github.com/raghuvaran/ha-addons/tree/main/spotify-yt-sync
arch:
  - aarch64
  - amd64
startup: once
boot: manual
init: false
options:
  youtube_playlist_id: ""
  youtube_refresh_token: ""
  google_client_id: ""
  google_client_secret: ""
  log_level: "info"
schema:
  youtube_playlist_id: str
  youtube_refresh_token: str
  google_client_id: str
  google_client_secret: str
  log_level: str?
map:
  - config:rw
